### PR TITLE
Modified Signer the remove DefaultHeaders from Request.

### LINKED ISSUE #28: Default Request Headers are double added on Android
**Describe the bug**
A HttpClient with `client.DefaultRequestHeaders.Add("x-api-key", myApiKey);` is signed correctly, but the client itself adds the header twice into the request:

    "Headers": [
    {
      "Key": "x-api-key",
      "Value": [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      ]
    },
    {
      "Key": "X-Amz-Date",
      "Value": [
    ...
    }

**To Reproduce**
Try this code:

    var client = new HttpClient();
    client.DefaultRequestHeaders.Add("x-api-key", accessToken);
    
    // do a random request
    var response = await client.GetAsync(requestUri, cancellationToken, regionName, serviceName, credentials);

You can see the request object before sending [here](https://github.com/FantasticFiasco/aws-signature-version-4/blob/master/src/SendAsyncExtensions.cs#L247).

Compare to the request object that is return in `response.RequestMessage`.

**Expected behavior**
The Request Header should contain the header "x-api-key" only once. Like this:

    "Headers": [
    {
      "Key": "x-api-key",
      "Value": [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      ]
    },
    {
      "Key": "X-Amz-Date",
      "Value": [
    ...
    }

**Environment (please complete the following information):**
- AWS API Gateway]
- OS: Android 8.0
- .NET version: Mono.Android

**Additional context**
I have tested an .NET Core 2.1 Console application where everything runs fine.

### PR DESCRIPTION
**Pull request by daniel-rck**
# Description

Fixes #28 

# Checklist

- [X] I have squashed my commits into a single one with a message that aligns with the contributing guidelines
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Don't worry about the failing CI, I caused it but will fix it before we merge this pull request.

**Comment by FantasticFiasco** [comment]
I am a couple commits away from being finished. But in the meantime I am forced to do changes to your master that won't work for you in Mono. I will try to be quick about it. If it is a problem for you, create a branch from your first commit and take a dependency on that until I am finished here.

Thanks!

**Comment by daniel-rck** [comment]
Don't feel pushed, I'm using my own fork until you release a stable version :)

**Comment by FantasticFiasco** [comment]
But I am pushing changes to your fork right now, in order to get them into the pull request, thus possibly affecting your development environment.

**Comment by daniel-rck** [comment]
Ah I see. Then I'll work with a local branch.

**Pull request merged**
